### ISSUE TITLE
非常喜欢作者的的这个设计

### ISSUE THREAD

**Issue by forsigner** [Kaiyuan/sponsor-page#1]
@Kaiyuan 非常喜欢你这个donate的设计，但是donate-page依赖了JQ，而且使用了iframe，这个不能很好的整合我的项目里去，能不能去掉JQ的依赖？

**Comment by Kaiyuan** [comment]
jQuery 是用来触发点击后换 class 方便的，你可以根据 script.js 文件132 行之后的内容修改成原生 JavaScript 就可以了。使用 jQuery 是因为写起来逻辑清晰而且方便。暂时我没有修改的计划。

**Comment by forsigner** [comment]
@Kaiyuan 能不能fork你的设计，我用原生JS写一份

**Comment by Kaiyuan** [comment]
当然可以！

**Comment by forsigner** [comment]
thx~
