### ISSUE TITLE
很认真地问一下这是哪边的原创？

### ISSUE THREAD

**Issue by mashirozx** [Kaiyuan/sponsor-page#2]
https://github.com/ihoey/Playing-reward

根据Commit记录看应该是那边抄袭的？

![image](https://user-images.githubusercontent.com/16148054/40237818-14bb80e0-5ae4-11e8-959e-c471dd0f09db.png)
![image](https://user-images.githubusercontent.com/16148054/40237831-1e39d478-5ae4-11e8-87b2-210547ed9060.png)

因为使用的时候要注明项目地址，所以这个问题蛮在意的。

**Comment by Kaiyuan** [comment]
当然我的是原创，[https://www.v2ex.com/t/275867](https://www.v2ex.com/t/275867)

**Comment by mashirozx** [comment]
@Kaiyuan 了解
